source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JSONModelTrial_Example', :exclusive => true do
    pod 'JSONModel'
  pod 'JSONModelTrial', :path => '../'
end

target 'JSONModelTrial_Tests', :exclusive => true do
  pod 'JSONModelTrial', :path => '../'

  
end
